#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# export TERM='rxvt-256color'

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# nvm
export NVM_DIR="$XDG_DATA_HOME/nvm"

# npm
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

# git
export GIT_REVIEW_BASE=master # See gitconfig

# less
export LESSHISTFILE="$XDG_STATE_HOME/less/history"

# docker 
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

#vim
export VIMINIT="set nocp | source $XDG_CONFIG_HOME/vim/vimrc"
